name: Upload Python Package with Poetry

on:
  release:
    types: [published]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment:
      name: pypi
      url: https://pypi.org/p/tribusen
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies with Poetry
        run: |
          poetry install
      - name: Build package with Poetry
        run: poetry build

      - name: Print PyPI Token Issuer
        run: |
          echo "Issuer: $(echo ${{ secrets.PYPI_TOKEN }})"

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            password: ${{ secrets.PYPI_TOKEN }}
            username: "__token__"
            
  
        
